const monsterColours = [
	"white",
	"orange",
	"pink",
	"purple",
	"gold",
	"red",
	"black",
	"peach",
];

export const throwableItems: string[] = [
	"a boom box",
	"old cheese",
	"a dirty needle",
	"a soft knife",
	"a sharp pillow",
	"a tomato",
	"debt",
	"the wednesday frog",
	"a very big fish",
	"Donald Trump's wall",
	"some tide pods",
	"divorce papers",
	"an engagement ring",
	"an 8ball",
	"gold coins",
	"a bus",
	"a football stadium",
	"the stanley cup",
	"a duck",
	"a discord channel",
	"a chair",
	"an AC-130",
	"an enchantment table",
	"a de-synced scav",
	"Jake from Statefarm",
	"the guy from fortnite",
	"a flashbang",
	"a maxed-out credit card",
	"a black hole",
	"some crappy code",
	"questionable life advice",
	"a fake rolex",
	"a real rolex",
	"some grass",
	"a terrible joke",
	"General Grievous's lightsaber collection",
	"a car",
	"expensive cheese",
	"the sun",
	"a rickroll",
	"an easter egg",
	"an overpowered pulse rifle",
	"a victory royale crown",
	"an alarm clock",
	"a C4 brick",
	"a sponge with square pants",
	"ADHD manifest",
	"a train",
	"Desmond the Moon Bear",
	"cats",
	"a bar of soap",
	"a job application form",
	"the evil tax man",
	"a plate of spaghetti",
	"a cringe anime trope",
	"the isekai truck",
	"a useless goddess",
	"a vape",
	"a bottle of Captain Morgan",
	`a ${
		monsterColours[Math.floor(Math.random() * monsterColours.length)]
	} monster`,
	"a not so happy happy-meal",
];
